//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duracellko.ClipboardShareUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duracellko.ClipboardShareUI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured while saving settings..
        /// </summary>
        internal static string Error_ConfigurationSaveFailed {
            get {
                return ResourceManager.GetString("Error_ConfigurationSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is empty..
        /// </summary>
        internal static string Error_EmptyUserName {
            get {
                return ResourceManager.GetString("Error_EmptyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help file &quot;Clipboard Share.pdf&quot; was not found or Acrobat Reader is not installed..
        /// </summary>
        internal static string Error_HelpNotFound {
            get {
                return ResourceManager.GetString("Error_HelpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max received message size must be positive number..
        /// </summary>
        internal static string Error_InvalidMaxReceivedMessageSize {
            get {
                return ResourceManager.GetString("Error_InvalidMaxReceivedMessageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port must be positive number..
        /// </summary>
        internal static string Error_InvalidServicePort {
            get {
                return ResourceManager.GetString("Error_InvalidServicePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard sharing did not start. See log for details..
        /// </summary>
        internal static string Error_StartingService {
            get {
                return ResourceManager.GetString("Error_StartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard sharing error.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during uninstallation..
        /// </summary>
        internal static string Error_Uninstall {
            get {
                return ResourceManager.GetString("Error_Uninstall", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Icon_ClipboardShare {
            get {
                object obj = ResourceManager.GetObject("Icon_ClipboardShare", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_AuthorizationBackground {
            get {
                object obj = ResourceManager.GetObject("Image_AuthorizationBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Cancel {
            get {
                object obj = ResourceManager.GetObject("Image_Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Delete {
            get {
                object obj = ResourceManager.GetObject("Image_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_DeleteAll {
            get {
                object obj = ResourceManager.GetObject("Image_DeleteAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Error {
            get {
                object obj = ResourceManager.GetObject("Image_Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Information {
            get {
                object obj = ResourceManager.GetObject("Image_Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Logo {
            get {
                object obj = ResourceManager.GetObject("Image_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Ok {
            get {
                object obj = ResourceManager.GetObject("Image_Ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Image_Warning {
            get {
                object obj = ResourceManager.GetObject("Image_Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in list....
        /// </summary>
        internal static string Text_NotInList {
            get {
                return ResourceManager.GetString("Text_NotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard Sharing.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peer Name Resolution Protocol (PNRP) is not installed. Other computers wouldn&apos;t discover clipboard sharing on this computer..
        /// </summary>
        internal static string Warning_PnrpNotInstalled {
            get {
                return ResourceManager.GetString("Warning_PnrpNotInstalled", resourceCulture);
            }
        }
    }
}
